import assert from "node:assert/strict";
import { test } from "node:test";
import { buildIdempotencyKey, PublishError, publishToWebsite, validatePublishRequest } from "./publish.ts";

const approved = {
  queueItemId: "raw-1:0",
  productCode: "RBR-A3-14",
  brandId: "rebar-ribbed-11",
  brandName: "ذوب آهن اصفهان",
  factoryPrice: 42000,
  warehousePrice: null,
  unit: "toman_per_kg",
  priceDate: "2026-08-20",
  reviewStatus: "approved",
  autoGenerated: false as const,
};

test("approved matched prices become a website payload without zeros", () => {
  const payload = validatePublishRequest(approved);
  assert.equal(payload.sku, "RBR-A3-14");
  assert.equal(payload.product_code, "RBR-A3-14");
  assert.equal(payload.factory_price_toman, 42000);
  assert.equal(payload.warehouse_price_toman, null);
  assert.equal(payload.auto_generated, false);
});

test("unapproved, unmatched, zero, and auto-generated requests are rejected", () => {
  assert.throws(() => validatePublishRequest({ ...approved, reviewStatus: "pending_review" }), PublishError);
  assert.throws(() => validatePublishRequest({ ...approved, productCode: null }), PublishError);
  assert.throws(() => validatePublishRequest({ ...approved, factoryPrice: 0 }), PublishError);
  assert.throws(() => validatePublishRequest({ ...approved, factoryPrice: null, warehousePrice: null }), PublishError);
  assert.throws(() => validatePublishRequest({ ...approved, autoGenerated: true }), PublishError);
});

test("idempotency key is stable for the same approved price", () => {
  const first = buildIdempotencyKey(approved);
  const second = buildIdempotencyKey(approved);
  assert.equal(first, second);
  assert.notEqual(first, buildIdempotencyKey({ ...approved, factoryPrice: 43000 }));
});

test("missing website credentials queue locally and do not invent a product", async () => {
  const previous = process.env.WEBSITE_API_BASE_URL;
  const previousKey = process.env.WEBSITE_API_KEY;
  delete process.env.WEBSITE_API_BASE_URL;
  delete process.env.WEBSITE_API_KEY;
  try {
    const result = await publishToWebsite(approved, async () => {
      throw new Error("should not send");
    });
    assert.equal(result.status, "queued");
    assert.equal(result.dryRun, true);
    assert.equal(result.productCode, "RBR-A3-14");
  } finally {
    if (previous === undefined) delete process.env.WEBSITE_API_BASE_URL;
    else process.env.WEBSITE_API_BASE_URL = previous;
    if (previousKey === undefined) delete process.env.WEBSITE_API_KEY;
    else process.env.WEBSITE_API_KEY = previousKey;
  }
});

test("website 409 is treated as an idempotent success", async () => {
  const previous = process.env.WEBSITE_API_BASE_URL;
  const previousKey = process.env.WEBSITE_API_KEY;
  process.env.WEBSITE_API_BASE_URL = "https://example.test";
  process.env.WEBSITE_API_KEY = "test-key";
  try {
    const result = await publishToWebsite(approved, async (payload) => ({
      operationId: payload.idempotency_key,
      accepted: true,
    }));
    assert.equal(result.status, "accepted");
    assert.equal(result.dryRun, false);
  } finally {
    if (previous === undefined) delete process.env.WEBSITE_API_BASE_URL;
    else process.env.WEBSITE_API_BASE_URL = previous;
    if (previousKey === undefined) delete process.env.WEBSITE_API_KEY;
    else process.env.WEBSITE_API_KEY = previousKey;
  }
});
