import { registeredRialToToman } from "../../web/src/intake/rial.ts";
import { findProductByCode, PRODUCTS } from "./catalog.ts";
import { getWebsiteConfig } from "./env.ts";

export class PublishError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PublishError";
  }
}

export type PriceType = "factory" | "warehouse";

export type PublishRequest = {
  queueItemId: string;
  productCode: string | null;
  brandId: string | null;
  brandName: string | null;
  factoryPrice: number | null;
  warehousePrice: number | null;
  unit: string | null;
  priceDate: string;
  reviewStatus: string;
  autoGenerated?: boolean;
  idempotencyKey?: string;
};

export type PublicationStatus = "queued" | "sent" | "accepted" | "rejected" | "failed";

export type PublicationResult = {
  queueItemId: string;
  productCode: string;
  brandId: string | null;
  brandName: string | null;
  factoryPrice: number | null;
  warehousePrice: number | null;
  unit: string | null;
  priceDate: string;
  idempotencyKey: string;
  status: PublicationStatus;
  autoGenerated: false;
  dryRun: boolean;
  websiteOperationId: string | null;
  errorMessage: string | null;
  payload: WebsitePublishPayload;
};

export type WebsitePublishPayload = {
  product_code: string;
  sku: string;
  brand_id: string | null;
  brand_name: string | null;
  factory_price_toman: number | null;
  warehouse_price_toman: number | null;
  unit: string | null;
  price_date: string;
  idempotency_key: string;
  auto_generated: false;
};

function assertPositiveOrNull(value: number | null, label: string): number | null {
  if (value === null || value === undefined) return null;
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new PublishError(`${label} نامعتبر است.`);
  }
  if (value === 0) throw new PublishError("قیمت صفر مجاز نیست. مقدار غایب باید null باشد.");
  if (value < 0) throw new PublishError("مبلغ منفی منتشر نمی‌شود.");
  return value;
}

export function buildIdempotencyKey(input: {
  queueItemId: string;
  productCode: string;
  priceDate: string;
  factoryPrice: number | null;
  warehousePrice: number | null;
}): string {
  return [
    input.queueItemId,
    input.productCode,
    input.priceDate,
    input.factoryPrice ?? "null",
    input.warehousePrice ?? "null",
  ].join(":");
}

export function validatePublishRequest(input: PublishRequest): WebsitePublishPayload {
  if (input.autoGenerated) {
    throw new PublishError("انتشار خودکار در پایلوت خاموش است.");
  }
  if (input.reviewStatus !== "approved") {
    throw new PublishError("فقط مشاهده تأییدشده توسط انسان قابل انتشار است.");
  }
  const productCode = input.productCode?.trim() ?? "";
  if (!productCode) {
    throw new PublishError("بدون product_code / sku وب‌سایت چیزی منتشر نمی‌شود.");
  }
  if (!findProductByCode(PRODUCTS, productCode)) {
    throw new PublishError("فقط sku موجود کاتالوگ وب‌سایت قابل انتشار است. محصول جدید ساخته نمی‌شود.");
  }
  const factoryRial = assertPositiveOrNull(input.factoryPrice, "قیمت کارخانه");
  const warehouseRial = assertPositiveOrNull(input.warehousePrice, "قیمت انبار");
  const factoryPrice = registeredRialToToman(factoryRial);
  const warehousePrice = registeredRialToToman(warehouseRial);
  if (factoryPrice === null && warehousePrice === null) {
    throw new PublishError("حداقل یکی از قیمت کارخانه یا انبار باید مقدار داشته باشد.");
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(input.priceDate)) {
    throw new PublishError("تاریخ قیمت باید به صورت YYYY-MM-DD باشد.");
  }
  const queueItemId = input.queueItemId.trim();
  if (!queueItemId) throw new PublishError("شناسه صف بررسی لازم است.");
  const idempotencyKey =
    input.idempotencyKey?.trim() ||
    buildIdempotencyKey({
      queueItemId,
      productCode,
      priceDate: input.priceDate,
      factoryPrice,
      warehousePrice,
    });
  return {
    product_code: productCode,
    sku: productCode,
    brand_id: input.brandId?.trim() || null,
    brand_name: input.brandName?.trim() || null,
    factory_price_toman: factoryPrice,
    warehouse_price_toman: warehousePrice,
    unit: input.unit?.trim() || null,
    price_date: input.priceDate,
    idempotency_key: idempotencyKey,
    auto_generated: false,
  };
}

export async function publishToWebsite(
  input: PublishRequest,
  send: (payload: WebsitePublishPayload) => Promise<{ operationId: string | null; accepted: boolean; error?: string }> = sendWebsitePayload,
): Promise<PublicationResult> {
  const payload = validatePublishRequest(input);
  const config = getWebsiteConfig();
  const base: Omit<PublicationResult, "status" | "dryRun" | "websiteOperationId" | "errorMessage"> = {
    queueItemId: input.queueItemId.trim(),
    productCode: payload.product_code,
    brandId: payload.brand_id,
    brandName: payload.brand_name,
    factoryPrice: payload.factory_price_toman,
    warehousePrice: payload.warehouse_price_toman,
    unit: payload.unit,
    priceDate: payload.price_date,
    idempotencyKey: payload.idempotency_key,
    autoGenerated: false,
    payload,
  };

  if (!config.configured) {
    return {
      ...base,
      status: "queued",
      dryRun: true,
      websiteOperationId: null,
      errorMessage: "کلید یا آدرس API وب‌سایت تنظیم نشده. انتشار در صف محلی ماند و کالا ساخته نشد.",
    };
  }

  try {
    const result = await send(payload);
    if (!result.accepted) {
      return {
        ...base,
        status: "rejected",
        dryRun: false,
        websiteOperationId: result.operationId,
        errorMessage: result.error ?? "وب‌سایت انتشار را رد کرد. قیمت محلی عوض نشد.",
      };
    }
    return {
      ...base,
      status: "accepted",
      dryRun: false,
      websiteOperationId: result.operationId,
      errorMessage: null,
    };
  } catch (error) {
    return {
      ...base,
      status: "failed",
      dryRun: false,
      websiteOperationId: null,
      errorMessage: error instanceof Error ? error.message : "ارسال به وب‌سایت انجام نشد.",
    };
  }
}

async function sendWebsitePayload(payload: WebsitePublishPayload): Promise<{
  operationId: string | null;
  accepted: boolean;
  error?: string;
}> {
  const config = getWebsiteConfig();
  const url = `${config.baseUrl}${config.publishPath.startsWith("/") ? "" : "/"}${config.publishPath}`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${config.apiKey}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });
  const text = await response.text();
  let parsed: { operation_id?: string; id?: string; error?: string } = {};
  try {
    parsed = JSON.parse(text) as typeof parsed;
  } catch {
    parsed = {};
  }
  if (response.status === 409) {
    return {
      operationId: parsed.operation_id ?? parsed.id ?? payload.idempotency_key,
      accepted: true,
    };
  }
  if (!response.ok) {
    return {
      operationId: parsed.operation_id ?? parsed.id ?? null,
      accepted: false,
      error: parsed.error ?? `وب‌سایت پاسخ ${response.status} داد.`,
    };
  }
  return {
    operationId: parsed.operation_id ?? parsed.id ?? payload.idempotency_key,
    accepted: true,
  };
}
