import type { DailyPrice } from "../../web/src/intake/dailyPriceStore.ts";
import { tehranDate } from "../../web/src/publish/publishStore.ts";
import { publishToWebsite } from "./publish.ts";

export type DailyPublishSummary = {
  accepted: number;
  queued: number;
  rejected: number;
  autoPublish: false;
};

export async function publishDailyRows(rows: DailyPrice[]): Promise<DailyPublishSummary> {
  const summary: DailyPublishSummary = { accepted: 0, queued: 0, rejected: 0, autoPublish: false };
  for (const row of rows) {
    if (!row.productCode.trim() || (row.factoryPrice == null && row.warehousePrice == null)) {
      summary.rejected += 1;
      continue;
    }
    try {
      const result = await publishToWebsite({
        queueItemId: `daily:${row.date}:${row.productCode}:${row.brandId ?? ""}`,
        productCode: row.productCode,
        brandId: row.brandId,
        brandName: row.brandName,
        factoryPrice: row.factoryPrice,
        warehousePrice: row.warehousePrice,
        unit: "rial_per_kg",
        priceDate: tehranDate(),
        reviewStatus: "approved",
        autoGenerated: false,
      });
      if (result.status === "accepted") summary.accepted += 1;
      else if (result.status === "queued") summary.queued += 1;
      else summary.rejected += 1;
    } catch {
      summary.rejected += 1;
    }
  }
  return summary;
}
