import assert from "node:assert/strict";
import { test } from "node:test";
import { canRequestPublish, upsertPublication, type PublicationRecord } from "./publishStore.ts";

test("only approved catalog prices can be published", () => {
  assert.equal(
    canRequestPublish({ status: "approved", productCode: "RBR-A3-14", factoryPrice: 42000, warehousePrice: null }),
    true,
  );
  assert.equal(
    canRequestPublish({ status: "pending_review", productCode: "RBR-A3-14", factoryPrice: 42000, warehousePrice: null }),
    false,
  );
  assert.equal(
    canRequestPublish({ status: "approved", productCode: null, factoryPrice: 42000, warehousePrice: null }),
    false,
  );
  assert.equal(
    canRequestPublish({ status: "approved", productCode: "RBR-A3-14", factoryPrice: 0, warehousePrice: null }),
    false,
  );
  assert.equal(
    canRequestPublish({ status: "approved", productCode: "RBR-A3-14", factoryPrice: null, warehousePrice: null }),
    false,
  );
});

test("replacing a publication by idempotency key does not duplicate", () => {
  const first: PublicationRecord = {
    id: "p1",
    queueItemId: "raw-1:0",
    productCode: "RBR-A3-14",
    brandId: null,
    brandName: null,
    factoryPrice: 42000,
    warehousePrice: null,
    unit: "toman_per_kg",
    priceDate: "2026-08-20",
    idempotencyKey: "raw-1:0:RBR-A3-14:2026-08-20:42000:null",
    status: "queued",
    autoGenerated: false,
    dryRun: true,
    websiteOperationId: null,
    errorMessage: null,
    requestedAt: "2026-08-20T00:00:00.000Z",
  };
  const next = upsertPublication([first], { ...first, id: "p2", status: "accepted", dryRun: false });
  assert.equal(next.length, 1);
  assert.equal(next[0]?.status, "accepted");
});
