const STORAGE_KEY = "price-update.publications.v1";

export type PublicationStatus = "queued" | "sent" | "accepted" | "rejected" | "failed";

export type PublicationRecord = {
  id: string;
  queueItemId: string;
  productCode: string;
  brandId: string | null;
  brandName: string | null;
  factoryPrice: number | null;
  warehousePrice: number | null;
  unit: string | null;
  priceDate: string;
  idempotencyKey: string;
  status: PublicationStatus;
  autoGenerated: false;
  dryRun: boolean;
  websiteOperationId: string | null;
  errorMessage: string | null;
  requestedAt: string;
};

export function tehranDate(): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran" }).format(new Date());
}

export function loadPublications(): PublicationRecord[] {
  try {
    if (typeof localStorage === "undefined") return [];
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as PublicationRecord[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function savePublications(items: PublicationRecord[]): void {
  if (typeof localStorage === "undefined") return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
}

export function findPublication(
  items: PublicationRecord[],
  queueItemId: string,
): PublicationRecord | undefined {
  return items.find((item) => item.queueItemId === queueItemId);
}

export function upsertPublication(
  items: PublicationRecord[],
  record: PublicationRecord,
): PublicationRecord[] {
  const without = items.filter(
    (item) => item.queueItemId !== record.queueItemId && item.idempotencyKey !== record.idempotencyKey,
  );
  return [record, ...without];
}

export function publicationStatusLabel(status: PublicationStatus): string {
  if (status === "accepted") return "پذیرفته‌شده در وب‌سایت";
  if (status === "queued") return "در صف محلی";
  if (status === "sent") return "ارسال‌شده";
  if (status === "rejected") return "ردشده توسط وب‌سایت";
  return "ناموفق";
}

export function canRequestPublish(item: {
  status: string;
  productCode: string | null;
  factoryPrice: number | null;
  warehousePrice: number | null;
}): boolean {
  if (item.status !== "approved") return false;
  if (!item.productCode?.trim()) return false;
  const factoryOk = item.factoryPrice !== null && item.factoryPrice > 0;
  const warehouseOk = item.warehousePrice !== null && item.warehousePrice > 0;
  return factoryOk || warehouseOk;
}
