import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useDailyPrices } from "../intake/DailyPriceState";
import { buildComparisonMatrix, flagLabel } from "../intake/compare";
import { tehranJalaliKey, tehranJalaliLabel } from "../intake/dates";
import { useIntakeState } from "../intake/IntakeState";
import { formatToman } from "../mock/data";
import { canRequestPublish, tehranDate } from "../publish/publishStore";
import { usePublishState } from "../publish/PublishState";
import { ResizableTable, ResizableTh } from "../tables/ResizableTh";

export function ComparePage() {
  const { items, decide } = useIntakeState();
  const { saveTarget } = useDailyPrices();
  const { record } = usePublishState();
  const rows = useMemo(() => buildComparisonMatrix(items), [items]);
  const rawCount = items.length;
  const [busyKey, setBusyKey] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function saveRow(row: (typeof rows)[number]) {
    setBusyKey(row.key);
    setError(null);
    setMessage(null);
    const saved = saveTarget({
      productCode: row.productCode,
      brandId: row.brandId,
      brandName: row.brandName,
      factoryPrice: row.targetFactory,
      warehousePrice: row.targetWarehouse,
      factorySource: row.factorySource,
      warehouseSource: row.warehouseSource,
      date: tehranJalaliKey(),
    });
    for (const quote of row.quotes) {
      if (quote.usable) decide(quote.queueId, "approved");
    }
    try {
      const payload = {
        queueItemId: `daily:${saved.date}:${saved.productCode}:${saved.brandId ?? ""}`,
        productCode: saved.productCode,
        brandId: saved.brandId,
        brandName: saved.brandName,
        factoryPrice: saved.factoryPrice,
        warehousePrice: saved.warehousePrice,
        unit: "rial_per_kg",
        priceDate: tehranDate(),
        reviewStatus: "approved" as const,
        autoGenerated: false,
      };
      if (canRequestPublish({ status: "approved", productCode: saved.productCode, factoryPrice: saved.factoryPrice, warehousePrice: saved.warehousePrice })) {
        const response = await fetch("/api/publish", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });
        const body = (await response.json()) as { status?: string; dryRun?: boolean; error?: string; errorMessage?: string };
        if (!response.ok) {
          setError(body.error ?? "ثبت جدول شد؛ ارسال به وب‌سایت انجام نشد.");
        } else {
          record({
            id: crypto.randomUUID(),
            queueItemId: payload.queueItemId,
            productCode: saved.productCode,
            brandId: saved.brandId,
            brandName: saved.brandName,
            factoryPrice: saved.factoryPrice,
            warehousePrice: saved.warehousePrice,
            unit: "rial_per_kg",
            priceDate: payload.priceDate,
            idempotencyKey: `${payload.queueItemId}:${payload.priceDate}`,
            status: (body.status as "queued" | "sent" | "accepted" | "rejected" | "failed") ?? "queued",
            autoGenerated: false,
            dryRun: Boolean(body.dryRun),
            websiteOperationId: null,
            errorMessage: body.errorMessage ?? null,
            requestedAt: new Date().toISOString(),
          });
        }
      }
      setMessage(`قیمت هدف ${row.productName} در جدول ${tehranJalaliLabel()} ثبت شد.`);
    } catch {
      setError("جدول محلی به‌روز شد؛ سرویس وب‌سایت در دسترس نیست.");
    } finally {
      setBusyKey(null);
    }
  }

  return (
    <section className="desk desk-wide">
      <header className="page-head">
        <div>
          <p className="kicker">ماتریس مقایسه</p>
          <h1>قیمت هدف {tehranJalaliLabel()}</h1>
        </div>
        <p className="page-head-note">
          فقط کالاهای کاتالوگ ما اینجاست. تاریخ قدیمی یا اختلاف زیاد علامت می‌خورد. حد بالای ردیف‌های سالم پیشنهاد
          می‌شود؛ ثبت، جدول روزانه را پر می‌کند و همان تغییر برای وب‌سایت صف می‌شود.
        </p>
      </header>

      <div className="settings-toolbar">
        <Link className="btn" to="/collect">
          دریافت منابع
        </Link>
        <Link className="btn" to="/review">
          صف بررسی
        </Link>
      </div>
      {message ? <p className="settings-banner">{message}</p> : null}
      {error ? <p className="settings-error">{error}</p> : null}

      {!rows.length ? (
        <div className="sheet">
          {rawCount === 0 ? (
            <>
              <p className="muted">
                هنوز قیمت تطبیق‌شده‌ای نیست. ماتریس خودش داده جمع نمی‌کند.
              </p>
              <p className="muted">یک‌بار «دریافت و تطبیق همه» را بزنید و تا پایان صبر کنید.</p>
              <Link className="btn primary" to="/collect">
                رفتن به دریافت
              </Link>
            </>
          ) : (
            <>
              <p className="muted">
                {rawCount.toLocaleString("fa-IR")} ردیف در صف هست، ولی هنوز به کالای کاتالوگ وصل نشده؛ برای همین ماتریس
                خالی است.
              </p>
              <p className="muted">همان دکمهٔ دریافت را دوباره بزنید، یا در صف بررسی «تطبیق دوباره» را بزنید.</p>
              <Link className="btn primary" to="/collect">
                دریافت و تطبیق دوباره
              </Link>
            </>
          )}
        </div>
      ) : (
        <div className="sheet table-wrap">
          <ResizableTable id="compare" className="price-table settings-table">
            <thead>
              <tr>
                <ResizableTh id="product">کالای ما</ResizableTh>
                <ResizableTh id="quotes">منابع</ResizableTh>
                <ResizableTh id="target">قیمت هدف</ResizableTh>
                <ResizableTh id="action"></ResizableTh>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.key}>
                  <td>
                    <strong>{row.productName}</strong>
                    <div className="muted">{row.brandName ?? "بدون کارخانه"}</div>
                  </td>
                  <td>
                    <ul className="compare-quotes">
                      {row.quotes.map((quote) => (
                        <li key={quote.queueId}>
                          <span>{quote.sourceName}</span>
                          <span>
                            کارخانه {formatToman(quote.factoryPrice)} · انبار {formatToman(quote.warehousePrice)}
                          </span>
                          {quote.flags.length ? (
                            <span className="badge warning">{quote.flags.map(flagLabel).join("، ")}</span>
                          ) : (
                            <span className="badge">{quote.usable ? "قابل استفاده" : quote.status}</span>
                          )}
                        </li>
                      ))}
                    </ul>
                  </td>
                  <td>
                    <div>کارخانه {formatToman(row.targetFactory)}</div>
                    <div>انبار {formatToman(row.targetWarehouse)}</div>
                    <div className="muted">حد بالای ردیف‌های سالم</div>
                  </td>
                  <td>
                    <button
                      className="btn slim primary"
                      type="button"
                      disabled={busyKey === row.key || (row.targetFactory == null && row.targetWarehouse == null)}
                      onClick={() => void saveRow(row)}
                    >
                      {busyKey === row.key ? "در حال ثبت…" : "ثبت در جدول"}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </ResizableTable>
        </div>
      )}
    </section>
  );
}
